app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catwiki.urls', namespace='catwiki'))
]

catwiki/urls.py
from django.urls import path

from . import views

app_name = 'catwiki'

urlpatterns = [
    path('', views.index, name='index'),
    path('searched', views.most_searched, name='searched'),
    path('detail/<str:breed_id>/', views.details_breed, name='detail'),
]

catwiki/forms.py
from django import forms
from .services import get_breeds


class SelectBreedForm(forms.Form):
    breeds = get_breeds('/breeds')
    breed = forms.CharField(label=False, widget=forms.Select(choices=breeds['list']))

catwiki/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import SelectBreedForm
from .services import get_breeds, get_breed_by_id, get_images, get_image_by_id, get_most_searched_breed


def index(request):
    if request.method == 'POST':
        form = SelectBreedForm(request.POST)

        if form.is_valid():
            breed = request.POST.get('breed')
            return HttpResponseRedirect('detail/' + breed)

    else:
        form = SelectBreedForm()

    breeds = get_breeds('/breeds')
    context = {
        'breeds': breeds['list'],
        'total_breeds': breeds['total'],
        'most_searched': {
            'beng': get_images('beng'),
            'sava': get_images('sava'),
            'norw': get_images('norw'),
            'esho': get_images('esho')
        },
        'form': form
    }

    return render(request, 'index.html', context)


def details_breed(request, breed_id):
    details_breed = get_breed_by_id(breed_id)
    context = {
        'name': details_breed['name'],
        'description': details_breed['description'],
        'skills_string': {
            'Temperament': details_breed['temperament'],
            'Origin': details_breed['origin'],
            'Life Span': details_breed['life_span'] + ' years',
        },
        'skills_number': {
            'Adaptability': details_breed['adaptability'],
            'Affection level': details_breed['affection_level'],
            'Child Friendly': details_breed['child_friendly'],
            'Grooming': details_breed['grooming'],
            'Intelligence': details_breed['intelligence'],
            'Health issues': details_breed['health_issues'],
            'Social needs': details_breed['social_needs'],
            'Stranger Friendly': details_breed['stranger_friendly']
        },
        'main_image': get_image_by_id(details_breed['reference_image_id']),
        'images': get_images(breed_id, limit=8)
    }

    return render(request, 'detail.html', context)


def most_searched(request):
    context = {
        'most_searched_breeds': get_most_searched_breed()
    }

    return render(request, 'searched.html', context)

catwiki/templates/base.html
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		<title>Catwiki</title>
		<meta name="description" content="Catwiki project based on devChallenges.io">
		<meta name="keywords" content="catwiki">
		<meta name="author" content="Margaux Dupuy">

		{% load static %}
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🐱</text></svg>">
		<link rel="stylesheet" href="{% static 'styles/styles.css' %}">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500;700&display=swap" rel="stylesheet">
        <script src="https://kit.fontawesome.com/39669ad7e7.js" crossorigin="anonymous"></script>
	</head>
	<header class="container mx-auto">
        <div class="px-16 py-8">
            <a href="/"><img src="{% static 'images/CatwikiLogo.svg' %}" alt="Catwiki Logo" class="" /></a>
        </div>
	</header>

	{% block content %}{% endblock %}

	<footer class="container mx-auto">
        <div class="flex flex-wrap items-center justify-center md:justify-between px-16 py-6 bg-black rounded-t-3xl">
            <img src="{% static 'images/CatwikiLogo_white.svg' %}" alt="Catwiki Logo" class="mb-8 md:mb-0"/>
            <div class="text-white text-sm">© created by Margaux Dupuy - devChallenges.io 2021</div>
        </div>
	</footer>

</html>

catwiki/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{%  block content %}

<body class="bg-grey-lightest font-serif leading-normal tracking-normal">

    <div class="container mx-auto">
        <section class="section-skills flex flex-col md:flex-row">
            <div class="w-full md:w-1/3 img-card p-8 md:p-16 md:pr-8">
                <img src="{{ main_image }}" alt="{{ name }}" class="rounded-3xl mx-auto w-full object-cover image-square"/>
            </div>

            <div class="w-full md:w-2/3 p-8 md:p-16 md:pr-8">
                <h1 class="text-lg">{{ name }}</h1>
                <p class="my-8">{{ description }}</p>

                <table id="breed-skills" class="table-auto text-sm">

                    {% for skill, str in skills_string.items %}
                        <tr>
                            <td class="font-bold pb-6">{{ skill }}</td>
                            <td class="pb-6 pl-6">{{ str }}</td>
                        </tr>
                    {% endfor %}

                    {% for skill, number in skills_number.items %}
                        <tr>
                            <td class="font-bold pb-6">{{ skill }}</td>
                            <td class="flex flex-row pt-3 pb-6 pl-6 skill-bars skill-{{ number }}">
                                <div class="bar-1"></div>
                                <div class="bar-2"></div>
                                <div class="bar-3"></div>
                                <div class="bar-4"></div>
                                <div class="bar-5"></div>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>

        </section>

        <section class="p-8 md:p-16 mb-6">
            <h2 class="text-lg">Others images</h2>
            <div class="md:grid md:grid-cols-2 md:grid-cols-4 gap-8 my-8">
                {% for url in images.url %}
                    <div class="img-card">
                        <img src="{{ url }}" alt="{{ images.name }}" class="rounded-3xl w-full object-cover mb-6" style="height: 250px;"/>
                    </div>
                {% endfor %}
            </div>
        </section>
    </div>
</body>

{% endblock %}

catwiki/templates/index.html
{% extends 'base.html' %}
{% load static %}

{%  block content %}

<body class="bg-grey-lightest font-serif leading-normal tracking-normal">

    <div class="container mx-auto">
        <section class="section-search flex flex-col text-center md:text-left">
            <h1 class="hidden">Catwiki</h1>
            <img src="{% static 'images/CatwikiLogo_white.svg' %}" alt="Catwiki Logo" style="width: 300px; height: auto;" />
            <p class="text-white my-4">Get to know more about your cat breed</p>
            <form action="/" method="post" class="mt-4">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Discover 🐱 → " class="text-sm mt-6 md:mt-0">
            </form>
        </section>

        <section class="section-most-searched bg-gray rounded-b-3xl p-8 md:p-16 mb-6">
            <span class="text-sm mb-4">Most Searched Breeds</span>
            <div class="flex flex-col md:flex-row justify-between items-end mt-4 mb-8">
                <h2 class="text-lg title-underline mb-8 md:mb-0">{{ total_breeds }}+ Breeds For you to discover</h2>
                <a href="{% url 'catwiki:searched' %}" class="text-sm uppercase text-secondary mb-2">See more <i class="fas fa-long-arrow-alt-right"></i></a>
            </div>

            <div class="md:grid md:grid-cols-4 gap-8">
                {% for id, cat in most_searched.items %}
                    <div class="img-card mb-12 md:mb-0">
                        <a href="{% url 'catwiki:detail' id %}">
                            <img src="{{ cat.image_url }}" alt="{{ cat.name }}" class="rounded-3xl w-full object-cover mx-auto sm:mx-0 mb-4 md:mb-6 image-square"/>
                            <div class="text-center md:text-left">{{ cat.name }}</div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </section>

        <section class="flex flex-col md:flex-row section-cat-reasons p-8 md:p-16 mb-6">
            <div class="md:w-5/12 md:pt-16">
                <h2 class="text-lg title-underline my-6">Why should you have a cat ?</h2>
                <p class="my-6">Having a cat around you can actually trigger the release of calming chemicals in your body which lower your stress and anxiety leves.</p>
                <a class="text-sm uppercase text-secondary my-6">Read More <i class="fas fa-long-arrow-alt-right"></i></a>
            </div>
            <div class="md:w-7/12 flex flex-col md:flex-row mt-8 md:mt-0">
                <div class="md:w-4/6 md:pl-12 md:pr-8">
                    <img src="{% static 'images/image 2.png' %}" alt="cat" class="rounded-3xl mb-8"/>
                    <img src="{% static 'images/image 1.png' %}" alt="cat" class="rounded-3xl mb-8 md:mb-0 md:float-right md:w-1/2"/>
                </div>
                <img src="{% static 'images/image 3.png' %}" alt="cat" class="flex-grow-0 md:w-2/6 rounded-3xl" style="height: fit-content;"/>
            </div>
        </section>

    </div>

</body>

{% endblock %}

catwiki/templates/searched.html
{% extends 'base.html' %}
{% load static %}

{%  block content %}

<body class="bg-grey-lightest font-serif leading-normal tracking-normal">

    <div class="container mx-auto p-8 md:p-16 mb-24">
        <section>
        <h1 class="text-lg font-bold my-8 ml-6">Top 10 most searched breeds</h1>
        {% with most_searched_breeds as list %}
        {% for breed in most_searched_breeds %}
           <div class="flex flex-col md:flex-row my-20">
               <img src="{{ breed.image }}" alt="{{ breed.name }}" class="rounded-3xl w-1/4 object-cover image-square mx-auto"/>
               <div  class="w-3/4 mt-6 md:mt-0 md:pl-6 mx-auto">
                   <a href="{% url 'catwiki:detail' breed.id %}"><h2 class="text-lg mb-6">{{ forloop.counter }}. {{ breed.name }}</h2></a>
                   <p>{{ breed.description }}</p>
               </div>
           </div>
        {% endfor %}
        {% endwith %}
        </section>
    </div>
</body>

{% endblock %}